# Generated by Django 5.2.8 on 2025-11-13 15:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('username', models.CharField(default='Anonymous', max_length=30)),
                ('emotion', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
            ],
        ),
    ]
